# Site settings
title: 3mily+
email: hello@emrcraig.com
url: https://3mily.github.io
description: "Just another online design portfolio"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  background: B8B8B8
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Emily Craig
  location: Around town
  social: Around the Web

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/emcrg
  - title: github
    url: http://github.com/3mily
  - title: linkedin
    url: http://www.linkedin.com/in/emrcraig

# Postal address (add as many lines as necessary)
# address:
#   - line: Vancouver, Canada

# # Credits content
# credits: 'Thanks Bootstrap!'

# Build settings
markdown: kramdown
permalink: pretty
